site_name: Anovos Docs
site_url: https://anovos.ai 
# Plugins
plugins:
  - search


theme:
  name: material
  logo: assets/logo.png
  custom_dir: overrides
  footer_logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
        primary: deep purple
    - scheme: slate 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/shortcuts.js

nav:
  - Home: index.md
  - About: about/index.md
  - Getting Started: getting-started/index.md
  - Community:
    - Contributing to Anovos: community/contributing/index.md
    - Code of Conduct: community/code-of-conduct/index.md
    - Communication: community/communication/index.md
    - License: community/license/index.md
  - In-Depth Docs: 
    - Anovos Intro: docs/anovos-intro/index.md
    - Setting Up Your Environment:
      - Anovos On Local: docs/setting-up-your-environment/anovos-on-local/index.md
      - Anovos on AWS: docs/setting-up-your-environment/anovos-on-aws/index.md
    - Anovos Product Roadmap: docs/anovos-roadmap/index.md
    - Anovos Potential Workflow: docs/anovos-potential-workflow/index.md
    - Anovos Modules: 
      - Overview: docs/anovos-modules-overview/overview/index.md
      - Data Ingest: docs/anovos-modules-overview/data-ingest/index.md
      - Data Analyzer: docs/anovos-modules-overview/data-analyzer/index.md
      - Quality Checker: docs/anovos-modules-overview/quality-checker/index.md
      - Association Evaluator: docs/anovos-modules-overview/association-evaluator/index.md
      - Data Drift and Stability Index: docs/anovos-modules-overview/data_drift_and_stability_index/index.md
      - Data Transformers: docs/anovos-modules-overview/data_transformer/index.md
    - Data Reports:
      - Overview: docs/data-reports/overview/index.md
      - Intermediate Report Data Generation: docs/data-reports/intermediate-report-data-generation/index.md
      - Final Report Generation: docs/data-reports/final-report-generation/index.md
      - HTML Report: docs/data-reports/html-report/index.md
    - Anovos on AWS EMR: docs/anovos-on-aws-emr/getting-started/index.md
    - Anovos Scale Testing: docs/anovos-scale-testing/overview/index.md
    


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anovos
    - icon: fontawesome/brands/slack
      link: https://go.mlops.community/slack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/anovos

extra:
  analytics:
    provider: google
    property: UA-52258647-20