site_name: Anovos Documentation
site_url: https://docs.anovos.ai
site_description: Stable Features yield Resilient Models. Documentation for the Feature Engineering Library Anovos.
site_author: Anovos Developers, Mobilewalla

repo_url: https://github.com/anovos/anovos-docs
repo_name: anovos/anovos-docs
edit_uri: edit/main/docs

use_directory_urls: false

plugins:
  - search
  - include_dir_to_nav
markdown_extensions:
  - fenced_code
  - pymdownx.arithmatex
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  logo: assets/logo.png
  custom_dir: overrides
  footer_logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

nav:
  - Home: index.md
  - About: about.md
  - Getting Started 🚀: getting-started.md
  - Using Anovos:
      - Setting up:
          - Locally: using-anovos/setting-up/locally.md
          - On AWS: using-anovos/setting-up/on_aws.md
          - Spark cluster: using-anovos/setting-up/spark_cluster.md
      - Workflow: using-anovos/workflow.md
      - Configuration: using-anovos/config_file.md
      - Data Reports:
          - Overview: using-anovos/data-reports/overview.md
          - Intermediate Report: using-anovos/data-reports/intermediate_report.md
          - Final Report: using-anovos/data-reports/final_report.md
          - HTML Report: using-anovos/data-reports/html_report.md
      - Feature Recommender: using-anovos/feature_recommender.md
      - Scaling Up: using-anovos/scaling.md
      - Limitations: using-anovos/limitations.md
      - Roadmap: using-anovos/roadmap.md
  - Community:
      - Contributing: community/contributing.md
      - Communication: community/communication.md
      - Code of Conduct: community/code-of-conduct.md
  - API Docs:
    - api
  - License: license.md

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anovos
    - icon: fontawesome/brands/slack
      link: https://go.mlops.community/slack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/anovos

  analytics:
    provider: google
    property: UA-52258647-20

  lib_repo_url: https://github.com/anovos/anovos
  lib_repo_name: anovos/anovos
