site_name: Anovos Docs
site_url: https://anovos.ai 
plugins:
  - search

theme:
  name: material
  logo: assets/logo.png
  custom_dir: overrides
  footer_logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
        primary: deep purple
    - scheme: slate 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/shortcuts.js

nav:
  - Home: index.md
  - About: about/index.md
  - Getting Started: getting-started/index.md
  - Using Anovos:
    - Setting up your environment:
      - Locally: docs/setting-up-your-environment/anovos-on-local/index.md
      - on AWS: docs/setting-up-your-environment/anovos-on-aws/index.md
    - Workflow: docs/anovos-potential-workflow/index.md
    - Data Reports:
      - Overview: docs/data-reports/overview/index.md
      - Intermediate Report Data Generation: docs/data-reports/intermediate-report-data-generation/index.md
      - Final Report Generation: docs/data-reports/final-report-generation/index.md
      - HTML Report: docs/data-reports/html-report/index.md
    - Scaling Up: docs/anovos-scale-testing/overview/index.md
    - Limitations: docs/limitations/index.md
    - Product Roadmap: docs/anovos-roadmap/index.md
  - Community:
      - Contributing to Anovos: community/contributing/index.md
      - Communication Channels: community/communication/index.md
      - Code of Conduct: community/code-of-conduct/index.md

  - License: community/license/index.md
  - API Docs:
      - Overview: docs/anovos-modules-overview/overview/index.md
      - Data Ingest: docs/anovos-modules-overview/data-ingest/index.md
      - Data Analyzer: docs/anovos-modules-overview/data-analyzer/index.md
      - Quality Checker: docs/anovos-modules-overview/quality-checker/index.md
      - Association Evaluator: docs/anovos-modules-overview/association-evaluator/index.md
      - Data Drift and Stability Index: docs/anovos-modules-overview/data_drift_and_stability_index/index.md
      - Data Transformers: docs/anovos-modules-overview/data_transformer/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anovos
    - icon: fontawesome/brands/slack
      link: https://go.mlops.community/slack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/anovos

  analytics:
    provider: google
    property: UA-52258647-20
