name: Build docs
on:
  pull_request:
    types:
      - opened
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build the docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Pip cache
        uses: actions/cache@v3.0.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-docs-${{ hashFiles('./requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-docs-

      - name: Install MkDocs
        run: |
          pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt

      - name: Build docs
        run: |
          mkdocs build --strict
