name: Publish docs
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - README.md

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Pip cache
        uses: actions/cache@v3.0.5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-docs-${{ hashFiles('./requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-docs-

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.25

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          CUSTOM_DOMAIN: docs.anovos.ai
          REQUIREMENTS: requirements.txt
